# yaml-language-server: $schema=https://unpkg.com/@powersync/service-schema@latest/json-schema/powersync-config.json

_type: self-hosted

replication:
  connections:
    - sslmode: disable
      type: postgresql
      uri: !env PS_DATA_SOURCE_URI

storage:
  sslmode: disable
  type: postgresql
  uri: !env PS_DATA_SOURCE_URI

port: !env PS_PORT

client_auth:
  jwks_uri: !env PS_BACKEND_JWKS_URI
  audience: [ "powersync-dev", "powersync", "authenticated" ]

telemetry:
  prometheus_port: 9090
  disable_telemetry_sharing: true
  enable_client_logging: true

api:
  tokens:
    - !env PS_ADMIN_TOKEN
